### ISSUE TITLE
do not display temperatures levels in "advanced"

### ISSUE THREAD

**Issue by leopoldhub** [YoCodingMonster/MSI-Dragon-Center-for-Linux#48]
![Screenshot from 2021-08-27 11-30-35](https://user-images.githubusercontent.com/21125567/131106235-ec156195-4aa0-4e07-84e0-cd221ddaaa8a.png)
![Screenshot from 2021-08-27 11-31-28](https://user-images.githubusercontent.com/21125567/131106242-8bf2891f-fac2-4949-b73e-5d73086d8f55.png)

In screenshot 2 all the temperature indicator show 0°C

**Comment by YoCodingMonster** [comment]
https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.1

have a look at the latest release and tell if it solved the problem or not!!

**Comment by YoCodingMonster** [comment]
also if the issue persists, please specify the system specifications and model number

**Comment by YoCodingMonster** [comment]
new release
